
title: David Schneller Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "davidschneller.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

collections_dir: collections

collections:
  portfolio:
    output: true

sass:
  sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - vendor
  
#   - node_modules
